name       : tealdeer
version    : 1.2.0
release    : 2
source     :
   - git|https://github.com/dbrgn/tealdeer : v1.2.0
license    : MIT
component  : programming.tools
homepage   : https://tldr.sh/
summary    : Simplified man pages with practial examples
description: |
    The TLDR pages are a community effort to simplify the beloved man pages with practical examples.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -D -m 00755 $workdir/target/release/tldr $installdir/usr/bin/tldr
    install -D -m 00644 $workdir/bash_tealdeer $installdir/usr/share/bash-completion/completions/tldr
    install -D -m 00644 $workdir/fish_tealdeer $installdir/usr/share/fish/completion/tldr.fish
    install -D -m 00644 $pkgfiles/zsh_tealdeer $installdir/usr/share/zsh/site-functions/_tldr
